# Generated by Django 6.0.3 on 2026-08-21 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'en attente'), ('accepted', 'acceptée'), ('rejeted', 'refusée'), ('cancelled', 'annulée')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='teachers.teachersubject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher_subject'), name='unique_booking_request')],
            },
        ),
    ]
